version: '3.9'
  services:
    zed2: 
      image: zed_ros2_built:latest
      build: .
      network_mode: "host"
      privileged: true
      deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                count: all
                capabilities: [gpu]
      command: nvidia-smi && ros2 launch zed_wrapper zed2.launch.py
      volumes:
        - type: bind
          source: /tmp/.X11-unix
          target: /tmp/.X11-unix
      environment:
        - DISPLAY=${DISPLAY}
        - NVIDIA_DRIVER_CAPABILITIES=all